server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:./h2db/temp;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
        descriptor:
          sql:
            BasicBinder: trace
        EnumType: trace
